//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainClientData
    {
        public MainClientData()
        {
            this.EyeClientDatas = new HashSet<EyeClientData>();
            this.OtherClientDatas = new HashSet<OtherClientData>();
            this.VisitDatas = new HashSet<VisitData>();
        }
    
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<EyeClientData> EyeClientDatas { get; set; }
        public virtual ICollection<OtherClientData> OtherClientDatas { get; set; }
        public virtual ICollection<VisitData> VisitDatas { get; set; }
    }
}
