//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherClientData
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual MainClientData MainClientData { get; set; }
    }
}
