//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitData
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<bool> Removed { get; set; }
    
        public virtual MainClientData MainClientData { get; set; }
    }
}
